# creating this secrets file for to store secrets in encoded format, used by mysql-deployment file
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=         # by encoding password
